FROM golang:1.19-alpine

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY cmd/ ./cmd/
COPY migrations/ ./migrations/
COPY pb/ ./pb/
COPY . .


COPY .env .env

RUN go build -o grpc ./cmd/grpc

EXPOSE 8080 50051 8081

CMD ["./grpc"]

