FROM golang:1.19-alpine as builder

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o graphql ./cmd/graphql

FROM alpine:latest  

WORKDIR /root/

COPY --from=builder /app/graphql .

EXPOSE 8081

CMD ["./graphql"]

